export const CardContainer = [
  {
    id: 1,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    name: "Roger Scott",
    title: "Marketing Manager",
  },
  {
    id: 2,
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    desc: "This service has been a game changer for our business. The team is always responsive and professional. Highly recommended!",
    name: "Jane Doe",
    title: "CEO, Tech Solutions",
  },
  {
    id: 3,
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    desc: "I'm extremely satisfied with the quality of service provided. They always go above and beyond to ensure our needs are met.",
    name: "John Smith",
    title: "Project Manager, ABC Corp",
  },
  {
    id: 4,
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    desc: "Their attention to detail and customer service is outstanding. They truly care about the success of our business.",
    name: "Emily Johnson",
    title: "Marketing Director, XYZ Inc",
  },
  {
    id: 5,
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    desc: "The team is knowledgeable, efficient, and easy to work with. They have exceeded our expectations in every way.",
    name: "Michael Brown",
    title: "CTO, Startup Co",
  },
  {
    id: 6,
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    desc: "Their innovative approach and creative solutions have significantly improved our business operations. We're grateful for their partnership.",
    name: "Sarah Williams",
    title: "Operations Manager, DEF Ltd",
  },
  {
    id: 7,
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    desc: "They consistently deliver high-quality results. Their technical expertise and commitment to excellence are evident in their work.",
    name: "David Miller",
    title: "Product Manager, GHI Inc",
  },
  {
    id: 8,
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    desc: "Their professionalism and dedication are unmatched. They've helped us streamline our processes and increase productivity.",
    name: "Laura Thompson",
    title: "HR Director, JKL Enterprises",
  },
  {
    id: 9,
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    desc: "Their services have been instrumental in our company's growth and success. We can always count on them for reliable and efficient solutions.",
    name: "Robert Wilson",
    title: "CEO, MNO Industries",
  },
  {
    id: 10,
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    desc: "Their team is always responsive and ready to assist. Their services have been invaluable to our company.",
    name: "Jessica Taylor",
    title: "CFO, PQR Corp",
  },
  {
    id: 11,
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    desc: "Their innovative solutions have helped us improve efficiency and productivity. Highly recommended!",
    name: "James Davis",
    title: "CTO, STU Inc",
  },
  {
    id: 12,
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    desc: "Their commitment to customer satisfaction is evident in their high-quality services. We're glad to be working with them.",
    name: "Patricia Moore",
    title: "COO, VWX Co",
  },
  {
    id: 13,
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    desc: "Their team is professional and easy to work with. Their services have exceeded our expectations.",
    name: "Richard Jackson",
    title: "CEO, YZ Corp",
  },
  {
    id: 14,
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    desc: "Their services have been instrumental in our company's success. We're grateful for their partnership.",
    name: "Linda Harris",
    title: "CFO, ABC Inc",
  },
  {
    id: 15,
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    desc: "Their team is knowledgeable and efficient. Their services have significantly improved our business operations.",
    name: "Joseph Martin",
    title: "CTO, DEF Co",
  },
  {
    id: 16,
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    desc: "Their innovative approach and creative solutions have been a game changer for our business. Highly recommended!",
    name: "Susan Clark",
    title: "COO, GHI Corp",
  },
  {
    id: 17,
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    desc: "Their professionalism and dedication are unmatched. They've helped us streamline our processes and increase productivity.",
    name: "William Rodriguez",
    title: "CEO, JKL Inc",
  },
  {
    id: 18,
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    desc: "Their professionalism and dedication are unmatched. They've helped us streamline our processes and increase productivity.",
    name: "William Rodriguez",
    title: "CEO, JKL Inc",
  },
];
